name: run-tests

on: [push, pull_request]

jobs:
    php-tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: [8.1, 8.0, 7.4]

        name: P${{ matrix.php }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: curl
                  coverage: none

            - name: Install dependencies
              run: composer install
            - name: Execute tests
              run: vendor/bin/phpunit
